In [1]:
pwd

'C:\\Users\\Darvin'

In [2]:
cd D:\Darvin\python training

D:\Darvin\python training


In [4]:
import pandas as pd
data=pd.read_csv('binary.csv')
data.head(2)

class  handicapped-infants  water-project  budget-resolution  \
0      0                    0              1                  0   
1      0                    0              1                  0   

   physician-fee-freeze  el-salvador-aid  religious-groups  \
0                     1                1                 1   
1                     1                1                 1   

   anti-satellite-test-ban  aid-to-nicaraguan-contras  immigration  \
0                        0                          0            1   
1                        0                          0            0   

   synfuels-corporation  education-spending  superfund  crime  \
0                     1                   1          1      1   
1                     0                   1          1      1   

   duty-free-exports  export-administration-act-south-africa  
0                  0                                       1  
1                  0                                       1

In [11]:
y=data.iloc[:,0]
x=data.iloc[:,1:13]
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=11)
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)


(348, 12)
(87, 12)
(348,)
(87,)


In [17]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB().fit(xtrain,ytrain)
pred_y=model.predict(xtest)
from sklearn.metrics import confusion_matrix
confusion_matrix(ytest,pred_y)

array([[35,  2],
       [ 1, 49]], dtype=int64)

In [28]:
from sklearn import svm
model=svm.SVC(kernel="linear")
model.fit(xtrain,ytrain)
pred_y=model.predict(xtest)
confusion_matrix(ytest,pred_y)

array([[36,  1],
       [ 2, 48]], dtype=int64)

In [29]:
from sklearn.svm import SVR
import numpy as np
n_sample,n_feature=10,5
np.random.seed(0)
y=np.random.randn(n_sample)
y

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [31]:
x=np.random.randn(n_sample,n_feature)
x

array([[-0.67246045, -0.35955316, -0.81314628, -1.7262826 ,  0.17742614],
       [-0.40178094, -1.63019835,  0.46278226, -0.90729836,  0.0519454 ],
       [ 0.72909056,  0.12898291,  1.13940068, -1.23482582,  0.40234164],
       [-0.68481009, -0.87079715, -0.57884966, -0.31155253,  0.05616534],
       [-1.16514984,  0.90082649,  0.46566244, -1.53624369,  1.48825219],
       [ 1.89588918,  1.17877957, -0.17992484, -1.07075262,  1.05445173],
       [-0.40317695,  1.22244507,  0.20827498,  0.97663904,  0.3563664 ],
       [ 0.70657317,  0.01050002,  1.78587049,  0.12691209,  0.40198936],
       [ 1.8831507 , -1.34775906, -1.270485  ,  0.96939671, -1.17312341],
       [ 1.94362119, -0.41361898, -0.74745481,  1.92294203,  1.48051479]])

In [34]:
parameter={'kernel':('linear','rbf','poly'),'c':[1.5,10],'gamma':['le-7','le-4']}

In [37]:
from sklearn import grid_search


ImportError: cannot import name 'grid_search' from 'sklearn' (D:\anaconda\lib\site-packages\sklearn\__init__.py)